### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by voldin912**

### CODE REVIEW

**Comment by giaongo** [comment]
After careful review, I have not identified any essential changes required for merging this pull request with our main project. Therefore, I will proceed to close it. Thank you for taking the time to review our work, and I wish you a wonderful day!

**Comment by voldin912** [comment]
I wanna join your team. Could you accept my offer?
I am good at MERN stack, Vue.JS, Laravel, C#, Java, C/C++ programming.
If you agree please contact with me. Thanks.

**Comment by giaongo** [comment]
Hi @Kishida624, 

Thank you so much for showing interest in our work.  Answerpedia was part of the school project work that has been closed  after the course ends (about 2-3 months ago). Can you tell me the reason why you would like to join this project as a collaborator? 

Regards, 
Giao Ngo

**Comment by voldin912** [comment]
Thanks for your reply.
I mean not Answerpedia but for your team. I am looking for a good team using React and Next.JS and your team looks very good.
I also proud of these skills myself. If we cooperate then get the better result I think. 
Best Regards.

**Comment by TaiNguyen2407** [comment]
Hi @Kishida624 , 

Thank you for your interest in joining the project/ team.

We are simply a group of students in the same university that cooperated together to build a project for learning purposes. We are not an established team or company or whatsoever.  We are not going to build projects and applications for business purposes either. 

We wanted to clarify information so that you have a better understanding of the project or even, us. 

However, If you are interested in developing Answerpedia further. Please feel free to fork the repository and develop it in your own style. 

Thank you
Tai

**Comment by voldin912** [comment]
Thanks for your answer.

**Pull request closed without merging**
